<script lang="ts">
  import PageLayout from '$lib/components/PageLayout.svelte';
  import ResponsiveImage from '$lib/components/ResponsiveImage.svelte';

  let { data } = $props();
</script>

<PageLayout
  title="Elotrack"
  description="About Elotrack - a player statistics tracker application for League of Legends"
>
  <center>
    <h1>Elotrack</h1>
  </center>

  <p>
    <b>Elotrack</b> was a tool similar to <a href="/projects/osutrack/">osu!track</a> designed to
    allow players of the game
    <a href="https://leagueoflegends.com/" target="_blank" rel="noopener noreferrer"
      >League of Legends</a
    > to track their rank and other statistics about their account over time. It came second in a
    considerable collection of similar tracker tools including
    <a href="/blog/building-robintrack/">Robintrack</a> and
    <a href="/projects/polotrack/">Polotrack</a>.
  </p>

  <h2>Current Status</h2>
  <p>
    Elotrack is no longer in existence. First of all, League of Legends is an extremely popular
    game, there were several much more mature and popular tools such as
    <a href="https://na.op.gg/" target="_blank" rel="noopener noreferrer">op.gg</a> and
    <a href="https://www.leaguespy.net/" target="_blank" rel="noopener noreferrer">LeagueSpy</a> that
    already filled the niche that this tool provided. As a result, this tool recieved basically zero
    attention or interest when I shared it, making my desire to work on and maintain it much
    smaller. My primitive web design skills at the time with the <code>&lt;table&gt;</code>-based
    UI, terrible color scheme, non-responsive design, and general lack of finesse and style didn't
    help either. Secondly, the API endpoint that was keeping Elotrack alive was deprecated and
    finally killed off entirely, taking Elotrack with it. It was originally hosted on the
    elotrack.net domain, but it has since expired and I've not renewed it.
  </p>

  <ResponsiveImage
    entry={data.images['elotrack/elotrack.png']}
    alt="A screenshot of the Elotrack interface"
    maxWidth={667}
    style="margin-bottom: 40px"
  />

  <h2>Tech Stack</h2>
  <p>
    Elotrack was built with a Ruby backend using the
    <a href="http://sinatrarb.com/" target="_blank" rel="noopener noreferrer">Sinatra</a> webserver
    framework. It used a MySQL database, some CLI scripts also written in Ruby and executed via Cron
    to generate some of the tables on the homepage and tablulate statistics, and had a frontend
    built with JQuery. Similarly to osu!track, much of the site content was generated by the Ruby
    with the resulting HTML being sent directly to the user. This was pretty much the last of my
    websites to be built in this manner; the rest were made using React and did most of their
    rendering client-side, pulling data from API endpoints.
  </p>
  <p>
    Despite not receiving any real traffic or popularity from users tracking their own accounts'
    stats, automated scripts ran periodically to track the top players in all of League of Legend's
    regions. A pretty hefty amount of data ended up being collected, which prompted me to put in the
    effort to learn how to optimize the database with proper indices and come up with a better
    schema. Many of the things I learned while working on Elotrack including how to manage a full
    database migration and better administer relational databases have proven useful on other
    projects since.
  </p>
</PageLayout>
