[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[dependencies]
nalgebra = "0.17.2"
ncollide2d = "0.18.2"
wasm-bindgen = "=0.2.47"
rand = "0.6.5"
rand_pcg = "0.1.1"
rand_core = "0.4.0"
console_error_panic_hook = "0.1.6"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
