[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[dependencies]
nalgebra = "0.18.1"
ncollide2d = "0.20.1"
wasm-bindgen = "=0.2.54"
rand = "0.7.0"
rand_pcg = "0.2.0"
rand_core = "0.5.1"
console_error_panic_hook = "0.1.6"

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
