[package]
authors = ["Casey Primozic <me@ameo.link>"]
edition = "2018"
name = "engine"
version = "0.1.0"

[dependencies]
nalgebra = "0.16.4"
ncollide2d = "0.17"
wasm-bindgen = "0.2.21"
rand = "0.5.5"
rand_pcg = "0.1.1"
rand_core = "0.3.0"

common = { git = "https://github.com/Ameobea/sketches.git" }

[lib]
crate-type = ["cdylib"]
