version: 2

jobs:
  build:
    docker:
      - image: node:11.6.0-stretch
    steps:
      - run: >
          apt-key adv --keyserver pool.sks-keyservers.net --recv 9D41F3C3 &&
          echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - run: apt-get update
      - run: apt-get install libssl-dev python3 libpython3-dev rsync curl bash cmake git build-essential -y
      - run: curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
      - run: chmod +x /tmp/rustup.sh
      - run: /tmp/rustup.sh -y --default-toolchain nightly
      - run: echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo install wasm-bindgen-cli
      # install `wasm-opt`
      - run: git clone https://github.com/WebAssembly/binaryen.git /tmp/binaryen
      - run: cd /tmp/binaryen && cmake . && make install
      - checkout
      - run: apt-get install yarn -y
      - run: yarn
      - run: bash ./build_all.sh
      - run: "echo $SSH_KEY | base64 -d > ~/.ssh/id_rsa"
      - run: chmod 600 ~/.ssh/id_rsa
      - run: rsync -Prv -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -F /dev/null" --delete ./public/* circleci@ameo.link:/var/www/cprimozic/

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
